#!/usr/bin/env python3
"""
new_domain.py — auto-wiki domain scaffold + cross-domain registry generator

One command creates a new domain (clone the skeleton + initialize data.db + write
meta/ontology/Hub/log + rebuild the registry), or rebuilds wiki/_index.md alone.

  # Create a new domain
  python new_domain.py tech \
      --direction Tech --central "AI industry chain" \
      --hub Tech --desc "AI / semiconductor / software cognitive layer" \
      --types "companies,products,indicators,mechanisms,events,analyses,sources" \
      --keywords "AI,LLM,semiconductor,chips,compute,GPU,Nvidia,domestic substitution,SaaS,Agent"

  # Only rebuild the registry (after any meta.yaml change)
  python new_domain.py --reindex

Design: meta.yaml is the single source of truth (incl. direction/hub/keywords);
_index.md is its derived view. The controlled relation vocabulary is not validated
here — it is a prose convention in _ontology.md, checked manually at lint
(schema.py is domain-agnostic).
"""
from __future__ import annotations
import argparse
import sys
from datetime import date
from pathlib import Path

# Reuse the engine's table creation (same directory as store.py)
sys.path.insert(0, str(Path(__file__).resolve().parent))
import store  # noqa: E402

try:
    import yaml
except ImportError:
    print("pyyaml is required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


# ── Locate the repo root (walk up to a directory containing CLAUDE.md) ──────
def find_repo_root() -> Path:
    p = Path(__file__).resolve()
    for parent in [Path.cwd(), *Path.cwd().parents, *p.parents]:
        if (parent / "CLAUDE.md").exists() and (parent / "wiki").exists():
            return parent
    # Fallback: references -> auto-wiki -> skills -> .claude -> repo
    return p.parents[4]


REPO = find_repo_root()
WIKI = REPO / "wiki"
TODAY = date.today().isoformat()


# ── Templates ────────────────────────────────────────────────────────────────
def meta_yaml(name, direction, central, desc, hub, keywords, validator, coverage) -> str:
    kw = ", ".join(keywords)
    return f"""name: {name}
domain: {name}
direction: {direction}          # Broad direction (Tech / Finance); _index.md groups by this
ontology_type: domain
description: {desc}
central_entity: {central}
hub: {hub}                       # Obsidian Hub page filename (without .md)
keywords: [{kw}]                 # Routing keywords: ingest/recall use these to decide which domain material belongs to
validator: {validator}
validator_coverage: {coverage}
schema_version: '2.0'
created: '{TODAY}'
updated: '{TODAY}'
"""


def ontology_md(name, direction, central, hub, types) -> str:
    type_rows = "\n".join(
        f"| ? | `{t}/` | <fill in criterion> | <fill in examples> |" for t in types
    )
    return f"""---
title: {hub} Domain Ontology Contract
type: ontology
domain: {name}
direction: {direction}
created: '{TODAY}'
updated: '{TODAY}'
schema_version: "2.0"
central_entity: {central}
tags: [ontology, contract]
---

# Air Vault · {hub} Domain Ontology Contract

> Ontology definition for `wiki/{name}/`. Read this page before `ingest`/`recall`. Engine spec lives in `.claude/skills/auto-wiki/`,
> and it **shares the same six-tier time model, retire-never-delete protocol and node/data/edge trichotomy** with [[_ontology|the macro ontology]] —
> **this page declares only the node types and controlled relation vocabulary specific to the {hub} domain**; everything else defers to the engine + macro contract.

## 0. Governing Principles (same as macro)
1. **Node / data / edge trichotomy**: a value is never a node (into data.db); a relation is an edge, not a page; a classification label is an edge, not a page.
2. **One-way compilation**: `Inbox (prose) → ingest → wiki (ontology)`. Rigor applies only to crystallized knowledge.
3. **Retire, never delete**: any T1/T2/T3 change means "seal the old row's valid_to + insert a new row", never DELETE, always stamped by a T4 event.

## 1. Node Criterion (same as macro's "can you point at this very one")
Can point a finger at "this very one", and the same name still points to the same thing next year → **entity**; needs a mechanism explanation first to be understood → **concept**.

## 2. Node Types (= directories = graph coloring)
| Type | Subdirectory | Criterion | Examples |
|---|---|---|---|
{type_rows}

> ⚠️ Placeholder table generated by the scaffold — before the first ingest you **must** fill in each row's criterion/examples and delete this notice.

## 3. Controlled Relation Vocabulary ({hub}-specific; generic terms references/part_of/instance_of etc. inherit from macro)
<Declare this domain's relation terms here: from_type → to_type, one-line semantics. lint checks against this and rejects out-of-bound edges.>

## 4. Cross-domain Connections
When this domain acts as a driving layer, use `references` edges to other domains' "analysis/nodes" (e.g. {name}/analyses → equity/companies).
For cross-domain wikilinks just write the other domain's slug directly.
"""


def hub_md(name, direction, central, hub, types) -> str:
    sections = "\n".join(f"## {t}\n- \n" for t in types)
    return f"""---
title: {hub}
type: ontology
domain: {name}
direction: {direction}
updated: '{TODAY}'
tags: [hub, moc]
---

# {hub} Domain Wiki

> Central entity [[{central}]] · ontology contract in [[_ontology]] · data in data.db · direction: {direction}

## Knowledge Structure
```
(Fill in after the first ingest: radial map around the central entity)
```

{sections}"""


def log_md(name, hub) -> str:
    return f"""# {hub} Domain · ingest log

> Append one line per ingest: date · source material · added/updated nodes · relation edges · validation result.

## {TODAY}
- Domain created (new_domain.py scaffold). Awaiting first ingest.
"""


# ── Registry generation ──────────────────────────────────────────────────────
def reindex() -> str:
    domains = []
    for meta_path in sorted(WIKI.glob("*/meta.yaml")):
        m = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
        domains.append(m)

    by_dir: dict[str, list] = {}
    for m in domains:
        by_dir.setdefault(m.get("direction", "uncategorized"), []).append(m)

    lines = [
        "---",
        "title: wiki domain registry",
        "type: registry",
        f"updated: '{TODAY}'",
        "tags: [hub, moc, registry]",
        "---",
        "",
        "# Air Vault · wiki domain registry (auto-generated)",
        "",
        "> Generated by `new_domain.py --reindex` from each domain's `meta.yaml`; **do not hand-edit** (edit meta.yaml, then rebuild).",
        "> **Step 0 of ingest/recall is reading this page**: route material/questions to a domain via the routing keywords; if it spans multiple domains, dual-write + cross-domain edges.",
        "",
        f"Currently {len(domains)} domains, {len(by_dir)} directions.",
        "",
    ]
    for direction in sorted(by_dir):
        lines.append(f"## Direction: {direction}")
        lines.append("")
        lines.append("| Domain | Central entity | Scope | Routing keywords |")
        lines.append("|---|---|---|---|")
        for m in by_dir[direction]:
            hub = m.get("hub", m.get("name"))
            kws = m.get("keywords", []) or []
            kw = ", ".join(kws) if isinstance(kws, list) else str(kws)
            lines.append(
                f"| [[{hub}]] `{m.get('name')}/` | [[{m.get('central_entity','')}]] | "
                f"{m.get('description','')} | {kw} |"
            )
        lines.append("")

    out = "\n".join(lines)
    (WIKI / "_index.md").write_text(out, encoding="utf-8")
    return out


# ── Domain creation ──────────────────────────────────────────────────────────
def create_domain(args) -> None:
    name = args.name
    ddir = WIKI / name
    if ddir.exists():
        print(f"✗ Domain already exists: {ddir}", file=sys.stderr)
        sys.exit(1)

    types = [t.strip() for t in args.types.split(",") if t.strip()]
    keywords = [k.strip() for k in args.keywords.split(",") if k.strip()]
    hub = args.hub or name

    # 1. Directory skeleton
    ddir.mkdir(parents=True)
    for t in types:
        sub = ddir / t
        sub.mkdir()
        (sub / ".gitkeep").write_text("", encoding="utf-8")

    # 2. data.db (idempotent table creation)
    s = store.WikiStore(str(ddir))
    s.init_db()
    s.close()

    # 3. The four standard files
    (ddir / "meta.yaml").write_text(
        meta_yaml(name, args.direction, args.central, args.desc, hub,
                  keywords, args.validator, args.coverage), encoding="utf-8")
    (ddir / "_ontology.md").write_text(
        ontology_md(name, args.direction, args.central, hub, types), encoding="utf-8")
    (ddir / f"{hub}.md").write_text(
        hub_md(name, args.direction, args.central, hub, types), encoding="utf-8")
    (ddir / "log.md").write_text(log_md(name, hub), encoding="utf-8")

    # 4. Rebuild the registry
    reindex()

    print(f"✓ Domain created: wiki/{name}/")
    print(f"  Type subdirectories: {', '.join(types)}")
    print(f"  data.db initialized | meta.yaml/_ontology.md/{hub}.md/log.md generated")
    print(f"  wiki/_index.md rebuilt (direction: {args.direction})")
    print(f"  ⚠️ Next step: manually fill in the type criterion table + relation vocabulary in wiki/{name}/_ontology.md, then ingest")


def main():
    ap = argparse.ArgumentParser(description="auto-wiki domain scaffold")
    ap.add_argument("name", nargs="?", help="Domain name (English slug, e.g. tech)")
    ap.add_argument("--direction", default="uncategorized", help="Broad direction: Tech / Finance")
    ap.add_argument("--central", default="", help="Central entity (slug)")
    ap.add_argument("--desc", default="", help="One-line scope description")
    ap.add_argument("--hub", default="", help="Hub page name (without .md, defaults to the domain name)")
    ap.add_argument("--types", default="institutions,indicators,mechanisms,events,analyses,sources",
                    help="Node type subdirectories, comma-separated")
    ap.add_argument("--keywords", default="", help="Routing keywords, comma-separated")
    ap.add_argument("--validator", default="fibo-mcp")
    ap.add_argument("--coverage", default="partial")
    ap.add_argument("--reindex", action="store_true", help="Only rebuild wiki/_index.md")
    args = ap.parse_args()

    if args.reindex:
        reindex()
        print("✓ wiki/_index.md rebuilt")
        return
    if not args.name:
        ap.error("Creating a domain requires a domain name; or use --reindex to only rebuild the registry")
    create_domain(args)


if __name__ == "__main__":
    main()
